package com.maiseries.core.bank.web.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_arc_person", "ID", ArcPerson.class);
		arp.addMapping("t_award_chance_info", "ID", AwardChanceInfo.class);
		arp.addMapping("t_award_info", "ID", AwardInfo.class);
		arp.addMapping("t_base_info", "ID", BaseInfo.class);
		arp.addMapping("t_batch_send_sms", "ID", BatchSendSms.class);
		arp.addMapping("t_contact_number", "id", ContactNumber.class);
		arp.addMapping("t_dic_region", "id", DicRegion.class);
		arp.addMapping("t_dic_system", "ID", DicSystem.class);
		arp.addMapping("t_finance_clear_list", "ID", FinanceClearList.class);
		arp.addMapping("t_invest_intent_info", "ID", InvestIntentInfo.class);
		arp.addMapping("t_item_info", "ID", ItemInfo.class);
		arp.addMapping("t_item_intro_list", "ID", ItemIntroList.class);
		arp.addMapping("t_loan_intent_info", "ID", LoanIntentInfo.class);
		arp.addMapping("t_message_content", "id", MessageContent.class);
		arp.addMapping("t_message_push", "id", MessagePush.class);
		arp.addMapping("t_order_info", "ID", OrderInfo.class);
		arp.addMapping("t_orderlist", "ID", Orderlist.class);
		arp.addMapping("t_payment_port", "ID", PaymentPort.class);
		arp.addMapping("t_person_account_info", "ID", PersonAccountInfo.class);
		arp.addMapping("t_person_prize", "ID", PersonPrize.class);
		arp.addMapping("t_repay_clear_list", "ID", RepayClearList.class);
		arp.addMapping("t_role_menu", "ID", RoleMenu.class);
		arp.addMapping("t_send_fail_info", "ID", SendFailInfo.class);
		arp.addMapping("t_settlement_port", "ID", SettlementPort.class);
		arp.addMapping("t_sms_info", "sms_id", SmsInfo.class);
		arp.addMapping("t_sys_menu", "ID", SysMenu.class);
		arp.addMapping("t_sys_notice", "ID", SysNotice.class);
		arp.addMapping("t_sys_role", "ID", SysRole.class);
		arp.addMapping("t_sys_user", "ID", SysUser.class);
		arp.addMapping("t_used_award_info", "ID", UsedAwardInfo.class);
		arp.addMapping("t_user_role", "ID", UserRole.class);
		arp.addMapping("t_whitelists_info", "ID", WhitelistsInfo.class);
	}
}

