package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseArcPerson;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArcPerson extends BaseArcPerson<ArcPerson> {
	
}
