package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseAwardChanceInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AwardChanceInfo extends BaseAwardChanceInfo<AwardChanceInfo> {
	
}
