package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseAwardInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AwardInfo extends BaseAwardInfo<AwardInfo> {
	
}
