package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseBaseInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BaseInfo extends BaseBaseInfo<BaseInfo> {
	
}
