package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseBatchSendSms;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BatchSendSms extends BaseBatchSendSms<BatchSendSms> {
	
}
