package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseContactNumber;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ContactNumber extends BaseContactNumber<ContactNumber> {
	
}
