package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseDicRegion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicRegion extends BaseDicRegion<DicRegion> {
	
}
