package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseDicSystem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DicSystem extends BaseDicSystem<DicSystem> {
	
}
