package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseFinanceClearList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FinanceClearList extends BaseFinanceClearList<FinanceClearList> {
	
}
