package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseInvestIntentInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InvestIntentInfo extends BaseInvestIntentInfo<InvestIntentInfo> {
	
}
