package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseItemInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ItemInfo extends BaseItemInfo<ItemInfo> {
	
}
