package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseItemIntroList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ItemIntroList extends BaseItemIntroList<ItemIntroList> {
	
}
