package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseLoanIntentInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class LoanIntentInfo extends BaseLoanIntentInfo<LoanIntentInfo> {
	
}
