package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseMessageContent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessageContent extends BaseMessageContent<MessageContent> {
	
}
