package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseMessagePush;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MessagePush extends BaseMessagePush<MessagePush> {
	
}
