package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseOrderInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderInfo extends BaseOrderInfo<OrderInfo> {
	
}
