package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseOrderlist;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderlist extends BaseOrderlist<Orderlist> {
	
}
