package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BasePaymentPort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PaymentPort extends BasePaymentPort<PaymentPort> {
	
}
