package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BasePersonAccountInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonAccountInfo extends BasePersonAccountInfo<PersonAccountInfo> {
	
}
