package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BasePersonPrize;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PersonPrize extends BasePersonPrize<PersonPrize> {
	
}
