package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseRepayClearList;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RepayClearList extends BaseRepayClearList<RepayClearList> {
	
}
