package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseSendFailInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SendFailInfo extends BaseSendFailInfo<SendFailInfo> {
	
}
