package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseSettlementPort;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SettlementPort extends BaseSettlementPort<SettlementPort> {
	
}
