package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseSmsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SmsInfo extends BaseSmsInfo<SmsInfo> {
	
}
