package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseSysNotice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysNotice extends BaseSysNotice<SysNotice> {
	
}
