package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseUsedAwardInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsedAwardInfo extends BaseUsedAwardInfo<UsedAwardInfo> {
	
}
