package com.maiseries.core.bank.web.common.model;

import com.maiseries.core.bank.web.common.model.base.BaseWhitelistsInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WhitelistsInfo extends BaseWhitelistsInfo<WhitelistsInfo> {
	
}
