package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseContactNumber<M extends BaseContactNumber<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}

	public java.lang.String getAccountName() {
		return get("account_name");
	}

	public M setAccountId(java.lang.String accountId) {
		set("account_id", accountId);
		return (M)this;
	}

	public java.lang.String getAccountId() {
		return get("account_id");
	}

	public M setAccountType(java.lang.String accountType) {
		set("account_type", accountType);
		return (M)this;
	}

	public java.lang.String getAccountType() {
		return get("account_type");
	}

	public M setLocationCity(java.lang.String locationCity) {
		set("location_city", locationCity);
		return (M)this;
	}

	public java.lang.String getLocationCity() {
		return get("location_city");
	}

	public M setLocationProvince(java.lang.String locationProvince) {
		set("location_province", locationProvince);
		return (M)this;
	}

	public java.lang.String getLocationProvince() {
		return get("location_province");
	}

	public M setNameSort(java.lang.String nameSort) {
		set("name_sort", nameSort);
		return (M)this;
	}

	public java.lang.String getNameSort() {
		return get("name_sort");
	}

}
