package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDicRegion<M extends BaseDicRegion<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return get("text");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public M setPcode(java.lang.String pcode) {
		set("pcode", pcode);
		return (M)this;
	}

	public java.lang.String getPcode() {
		return get("pcode");
	}

	public M setStatue(java.lang.Integer statue) {
		set("statue", statue);
		return (M)this;
	}

	public java.lang.Integer getStatue() {
		return get("statue");
	}

}
