package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBaseInfo<M extends BaseBaseInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setMobilePhone(java.lang.String mobilePhone) {
		set("mobile_phone", mobilePhone);
		return (M)this;
	}

	public java.lang.String getMobilePhone() {
		return get("mobile_phone");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setNickName(java.lang.String nickName) {
		set("nick_name", nickName);
		return (M)this;
	}

	public java.lang.String getNickName() {
		return get("nick_name");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCustomerip(java.lang.String customerip) {
		set("customerip", customerip);
		return (M)this;
	}

	public java.lang.String getCustomerip() {
		return get("customerip");
	}

	public M setRegisterType(java.lang.String registerType) {
		set("register_type", registerType);
		return (M)this;
	}

	public java.lang.String getRegisterType() {
		return get("register_type");
	}

	public M setInviteCode(java.lang.String inviteCode) {
		set("invite_code", inviteCode);
		return (M)this;
	}

	public java.lang.String getInviteCode() {
		return get("invite_code");
	}

	public M setUserBirthday(java.util.Date userBirthday) {
		set("user_birthday", userBirthday);
		return (M)this;
	}

	public java.util.Date getUserBirthday() {
		return get("user_birthday");
	}

	public M setUserAddress(java.lang.String userAddress) {
		set("user_address", userAddress);
		return (M)this;
	}

	public java.lang.String getUserAddress() {
		return get("user_address");
	}

	public M setUserIncome(java.lang.String userIncome) {
		set("user_income", userIncome);
		return (M)this;
	}

	public java.lang.String getUserIncome() {
		return get("user_income");
	}

	public M setUserCheckTime(java.lang.String userCheckTime) {
		set("user_check_time", userCheckTime);
		return (M)this;
	}

	public java.lang.String getUserCheckTime() {
		return get("user_check_time");
	}

	public M setCardNumber(java.lang.String cardNumber) {
		set("card_number", cardNumber);
		return (M)this;
	}

	public java.lang.String getCardNumber() {
		return get("card_number");
	}

	public M setLevel(java.lang.String level) {
		set("level", level);
		return (M)this;
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public M setRealName(java.lang.String realName) {
		set("real_name", realName);
		return (M)this;
	}

	public java.lang.String getRealName() {
		return get("real_name");
	}

	public M setIdentityCard(java.lang.String identityCard) {
		set("identity_card", identityCard);
		return (M)this;
	}

	public java.lang.String getIdentityCard() {
		return get("identity_card");
	}

	public M setActivationMail(java.lang.String activationMail) {
		set("activation_mail", activationMail);
		return (M)this;
	}

	public java.lang.String getActivationMail() {
		return get("activation_mail");
	}

	public M setMailDate(java.lang.String mailDate) {
		set("mail_date", mailDate);
		return (M)this;
	}

	public java.lang.String getMailDate() {
		return get("mail_date");
	}

	public M setPram1(java.lang.String pram1) {
		set("pram1", pram1);
		return (M)this;
	}

	public java.lang.String getPram1() {
		return get("pram1");
	}

	public M setPasswordFlag(java.lang.String passwordFlag) {
		set("password_flag", passwordFlag);
		return (M)this;
	}

	public java.lang.String getPasswordFlag() {
		return get("password_flag");
	}

	public M setLockpassDate(java.lang.String lockpassDate) {
		set("lockpass_date", lockpassDate);
		return (M)this;
	}

	public java.lang.String getLockpassDate() {
		return get("lockpass_date");
	}

	public M setAccSeq(java.lang.String accSeq) {
		set("acc_seq", accSeq);
		return (M)this;
	}

	public java.lang.String getAccSeq() {
		return get("acc_seq");
	}

	public M setIsLoan(java.lang.String isLoan) {
		set("is_loan", isLoan);
		return (M)this;
	}

	public java.lang.String getIsLoan() {
		return get("is_loan");
	}

	public M setRegion(java.lang.String region) {
		set("region", region);
		return (M)this;
	}

	public java.lang.String getRegion() {
		return get("region");
	}

	public M setClientType(java.lang.String clientType) {
		set("client_type", clientType);
		return (M)this;
	}

	public java.lang.String getClientType() {
		return get("client_type");
	}

	public M setForgetPassword(java.lang.String forgetPassword) {
		set("forget_password", forgetPassword);
		return (M)this;
	}

	public java.lang.String getForgetPassword() {
		return get("forget_password");
	}

	public M setInvitationCode(java.lang.String invitationCode) {
		set("invitation_code", invitationCode);
		return (M)this;
	}

	public java.lang.String getInvitationCode() {
		return get("invitation_code");
	}

	public M setInvitedCode(java.lang.String invitedCode) {
		set("invited_code", invitedCode);
		return (M)this;
	}

	public java.lang.String getInvitedCode() {
		return get("invited_code");
	}

	public M setMainSerialNumber(java.lang.String mainSerialNumber) {
		set("main_serial_number", mainSerialNumber);
		return (M)this;
	}

	public java.lang.String getMainSerialNumber() {
		return get("main_serial_number");
	}

	public M setThetimeLogin(java.lang.String thetimeLogin) {
		set("thetime_login", thetimeLogin);
		return (M)this;
	}

	public java.lang.String getThetimeLogin() {
		return get("thetime_login");
	}

	public M setTryPaycodeFlag(java.lang.String tryPaycodeFlag) {
		set("try_paycode_flag", tryPaycodeFlag);
		return (M)this;
	}

	public java.lang.String getTryPaycodeFlag() {
		return get("try_paycode_flag");
	}

	public M setTrySpecialcodeFlag(java.lang.String trySpecialcodeFlag) {
		set("try_specialcode_flag", trySpecialcodeFlag);
		return (M)this;
	}

	public java.lang.String getTrySpecialcodeFlag() {
		return get("try_specialcode_flag");
	}

}
