package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSmsInfo<M extends BaseSmsInfo<M>> extends Model<M> implements IBean {

	public M setSmsId(java.lang.String smsId) {
		set("sms_id", smsId);
		return (M)this;
	}

	public java.lang.String getSmsId() {
		return get("sms_id");
	}

	public M setAuthCode(java.lang.String authCode) {
		set("auth_code", authCode);
		return (M)this;
	}

	public java.lang.String getAuthCode() {
		return get("auth_code");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setEncodeStr(java.lang.String encodeStr) {
		set("encode_str", encodeStr);
		return (M)this;
	}

	public java.lang.String getEncodeStr() {
		return get("encode_str");
	}

	public M setFkOrderInfoSerialNumber(java.lang.String fkOrderInfoSerialNumber) {
		set("fk_order_info_serial_number", fkOrderInfoSerialNumber);
		return (M)this;
	}

	public java.lang.String getFkOrderInfoSerialNumber() {
		return get("fk_order_info_serial_number");
	}

	public M setIp(java.lang.String ip) {
		set("ip", ip);
		return (M)this;
	}

	public java.lang.String getIp() {
		return get("ip");
	}

	public M setMessageType(java.lang.String messageType) {
		set("message_type", messageType);
		return (M)this;
	}

	public java.lang.String getMessageType() {
		return get("message_type");
	}

	public M setMobilePhone(java.lang.String mobilePhone) {
		set("mobile_phone", mobilePhone);
		return (M)this;
	}

	public java.lang.String getMobilePhone() {
		return get("mobile_phone");
	}

	public M setOperId(java.lang.String operId) {
		set("oper_id", operId);
		return (M)this;
	}

	public java.lang.String getOperId() {
		return get("oper_id");
	}

	public M setReturnCode(java.lang.String returnCode) {
		set("return_code", returnCode);
		return (M)this;
	}

	public java.lang.String getReturnCode() {
		return get("return_code");
	}

	public M setSendFlag(java.lang.String sendFlag) {
		set("send_flag", sendFlag);
		return (M)this;
	}

	public java.lang.String getSendFlag() {
		return get("send_flag");
	}

	public M setSendTime(java.lang.String sendTime) {
		set("send_time", sendTime);
		return (M)this;
	}

	public java.lang.String getSendTime() {
		return get("send_time");
	}

	public M setValidTime(java.lang.String validTime) {
		set("valid_time", validTime);
		return (M)this;
	}

	public java.lang.String getValidTime() {
		return get("valid_time");
	}

}
