package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseLoanIntentInfo<M extends BaseLoanIntentInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setSex(java.lang.String sex) {
		set("sex", sex);
		return (M)this;
	}

	public java.lang.String getSex() {
		return get("sex");
	}

	public M setPhoneNumber(java.lang.String phoneNumber) {
		set("phone_number", phoneNumber);
		return (M)this;
	}

	public java.lang.String getPhoneNumber() {
		return get("phone_number");
	}

	public M setAge(java.lang.String age) {
		set("age", age);
		return (M)this;
	}

	public java.lang.String getAge() {
		return get("age");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public M setIdNumber(java.lang.String idNumber) {
		set("id_number", idNumber);
		return (M)this;
	}

	public java.lang.String getIdNumber() {
		return get("id_number");
	}

	public M setNationality(java.lang.String nationality) {
		set("nationality", nationality);
		return (M)this;
	}

	public java.lang.String getNationality() {
		return get("nationality");
	}

	public M setEducation(java.lang.String education) {
		set("education", education);
		return (M)this;
	}

	public java.lang.String getEducation() {
		return get("education");
	}

	public M setLiveAddress(java.lang.String liveAddress) {
		set("live_address", liveAddress);
		return (M)this;
	}

	public java.lang.String getLiveAddress() {
		return get("live_address");
	}

	public M setLiveCity(java.lang.String liveCity) {
		set("live_city", liveCity);
		return (M)this;
	}

	public java.lang.String getLiveCity() {
		return get("live_city");
	}

	public M setLiveTime(java.lang.String liveTime) {
		set("live_time", liveTime);
		return (M)this;
	}

	public java.lang.String getLiveTime() {
		return get("live_time");
	}

	public M setIdType(java.lang.String idType) {
		set("id_type", idType);
		return (M)this;
	}

	public java.lang.String getIdType() {
		return get("id_type");
	}

	public M setMaritalStatus(java.lang.String maritalStatus) {
		set("marital_status", maritalStatus);
		return (M)this;
	}

	public java.lang.String getMaritalStatus() {
		return get("marital_status");
	}

	public M setReqNumber(java.lang.String reqNumber) {
		set("req_number", reqNumber);
		return (M)this;
	}

	public java.lang.String getReqNumber() {
		return get("req_number");
	}

	public M setReqLoanMoney(java.lang.String reqLoanMoney) {
		set("req_loan_money", reqLoanMoney);
		return (M)this;
	}

	public java.lang.String getReqLoanMoney() {
		return get("req_loan_money");
	}

	public M setReqLoanTime(java.lang.String reqLoanTime) {
		set("req_loan_time", reqLoanTime);
		return (M)this;
	}

	public java.lang.String getReqLoanTime() {
		return get("req_loan_time");
	}

	public M setReqLoanUse(java.lang.String reqLoanUse) {
		set("req_loan_use", reqLoanUse);
		return (M)this;
	}

	public java.lang.String getReqLoanUse() {
		return get("req_loan_use");
	}

	public M setRepaymentMethod(java.lang.String repaymentMethod) {
		set("repayment_method", repaymentMethod);
		return (M)this;
	}

	public java.lang.String getRepaymentMethod() {
		return get("repayment_method");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setEnterpriseName(java.lang.String enterpriseName) {
		set("enterprise_name", enterpriseName);
		return (M)this;
	}

	public java.lang.String getEnterpriseName() {
		return get("enterprise_name");
	}

	public M setEnterpriseType(java.lang.String enterpriseType) {
		set("enterprise_type", enterpriseType);
		return (M)this;
	}

	public java.lang.String getEnterpriseType() {
		return get("enterprise_type");
	}

	public M setRegistrationNumber(java.lang.Integer registrationNumber) {
		set("registration_number", registrationNumber);
		return (M)this;
	}

	public java.lang.Integer getRegistrationNumber() {
		return get("registration_number");
	}

	public M setRegistrationAddres(java.lang.String registrationAddres) {
		set("registration_addres", registrationAddres);
		return (M)this;
	}

	public java.lang.String getRegistrationAddres() {
		return get("registration_addres");
	}

	public M setLegalPersonName(java.lang.String legalPersonName) {
		set("legal_person_name", legalPersonName);
		return (M)this;
	}

	public java.lang.String getLegalPersonName() {
		return get("legal_person_name");
	}

	public M setLegalIdentityCard(java.lang.String legalIdentityCard) {
		set("legal_identity_card", legalIdentityCard);
		return (M)this;
	}

	public java.lang.String getLegalIdentityCard() {
		return get("legal_identity_card");
	}

	public M setCompanyActualAddres(java.lang.String companyActualAddres) {
		set("company_actual_addres", companyActualAddres);
		return (M)this;
	}

	public java.lang.String getCompanyActualAddres() {
		return get("company_actual_addres");
	}

	public M setLoanObject(java.lang.String loanObject) {
		set("loan_object", loanObject);
		return (M)this;
	}

	public java.lang.String getLoanObject() {
		return get("loan_object");
	}

	public M setAssetType(java.lang.String assetType) {
		set("asset_type", assetType);
		return (M)this;
	}

	public java.lang.String getAssetType() {
		return get("asset_type");
	}

	public M setIssueDate(java.util.Date issueDate) {
		set("issue_date", issueDate);
		return (M)this;
	}

	public java.util.Date getIssueDate() {
		return get("issue_date");
	}

	public M setTicketDate(java.util.Date ticketDate) {
		set("ticket_date", ticketDate);
		return (M)this;
	}

	public java.util.Date getTicketDate() {
		return get("ticket_date");
	}

	public M setIssueAmount(java.lang.String issueAmount) {
		set("issue_amount", issueAmount);
		return (M)this;
	}

	public java.lang.String getIssueAmount() {
		return get("issue_amount");
	}

}
