package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysNotice<M extends BaseSysNotice<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setNoticeTitle(java.lang.String noticeTitle) {
		set("notice_title", noticeTitle);
		return (M)this;
	}

	public java.lang.String getNoticeTitle() {
		return get("notice_title");
	}

	public M setNoticeContext(java.lang.String noticeContext) {
		set("notice_context", noticeContext);
		return (M)this;
	}

	public java.lang.String getNoticeContext() {
		return get("notice_context");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setCreateUser(java.lang.String createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public M setImageUrl(java.lang.String imageUrl) {
		set("image_url", imageUrl);
		return (M)this;
	}

	public java.lang.String getImageUrl() {
		return get("image_url");
	}

	public M setIsDel(java.lang.String isDel) {
		set("is_del", isDel);
		return (M)this;
	}

	public java.lang.String getIsDel() {
		return get("is_del");
	}

}
