package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRepayClearList<M extends BaseRepayClearList<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
		return (M)this;
	}

	public java.lang.String getBankAccount() {
		return get("bank_account");
	}

	public M setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
		return (M)this;
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public M setBankCode(java.lang.String bankCode) {
		set("bank_code", bankCode);
		return (M)this;
	}

	public java.lang.String getBankCode() {
		return get("bank_code");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public M setBranchBank(java.lang.String branchBank) {
		set("branch_bank", branchBank);
		return (M)this;
	}

	public java.lang.String getBranchBank() {
		return get("branch_bank");
	}

	public M setCardProvinceCode(java.lang.String cardProvinceCode) {
		set("card_province_code", cardProvinceCode);
		return (M)this;
	}

	public java.lang.String getCardProvinceCode() {
		return get("card_province_code");
	}

	public M setCardProvinceName(java.lang.String cardProvinceName) {
		set("card_province_name", cardProvinceName);
		return (M)this;
	}

	public java.lang.String getCardProvinceName() {
		return get("card_province_name");
	}

	public M setCardCityNo(java.lang.String cardCityNo) {
		set("card_city_no", cardCityNo);
		return (M)this;
	}

	public java.lang.String getCardCityNo() {
		return get("card_city_no");
	}

	public M setCardCityName(java.lang.String cardCityName) {
		set("card_city_name", cardCityName);
		return (M)this;
	}

	public java.lang.String getCardCityName() {
		return get("card_city_name");
	}

	public M setOrderStatus(java.lang.String orderStatus) {
		set("order_status", orderStatus);
		return (M)this;
	}

	public java.lang.String getOrderStatus() {
		return get("order_status");
	}

	public M setBaseInfoId(java.lang.String baseInfoId) {
		set("base_info_id", baseInfoId);
		return (M)this;
	}

	public java.lang.String getBaseInfoId() {
		return get("base_info_id");
	}

	public M setItemId(java.lang.String itemId) {
		set("Item_id", itemId);
		return (M)this;
	}

	public java.lang.String getItemId() {
		return get("Item_id");
	}

	public M setItemName(java.lang.String itemName) {
		set("item_name", itemName);
		return (M)this;
	}

	public java.lang.String getItemName() {
		return get("item_name");
	}

	public M setItemNo(java.lang.String itemNo) {
		set("item_no", itemNo);
		return (M)this;
	}

	public java.lang.String getItemNo() {
		return get("item_no");
	}

	public M setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
		return (M)this;
	}

	public java.lang.String getSerialNumber() {
		return get("serial_number");
	}

	public M setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.String getOrderNumber() {
		return get("order_number");
	}

	public M setInvestDate(java.util.Date investDate) {
		set("invest_date", investDate);
		return (M)this;
	}

	public java.util.Date getInvestDate() {
		return get("invest_date");
	}

	public M setInvestMountFee(java.math.BigDecimal investMountFee) {
		set("invest_mount_fee", investMountFee);
		return (M)this;
	}

	public java.math.BigDecimal getInvestMountFee() {
		return get("invest_mount_fee");
	}

	public M setIncome(java.math.BigDecimal income) {
		set("income", income);
		return (M)this;
	}

	public java.math.BigDecimal getIncome() {
		return get("income");
	}

	public M setRate(java.math.BigDecimal rate) {
		set("rate", rate);
		return (M)this;
	}

	public java.math.BigDecimal getRate() {
		return get("rate");
	}

	public M setPrincipalAndInterest(java.math.BigDecimal principalAndInterest) {
		set("principal_and_interest", principalAndInterest);
		return (M)this;
	}

	public java.math.BigDecimal getPrincipalAndInterest() {
		return get("principal_and_interest");
	}

	public M setInterestStartDate(java.util.Date interestStartDate) {
		set("interest_start_date", interestStartDate);
		return (M)this;
	}

	public java.util.Date getInterestStartDate() {
		return get("interest_start_date");
	}

	public M setFinanceEndDate(java.util.Date financeEndDate) {
		set("finance_end_date", financeEndDate);
		return (M)this;
	}

	public java.util.Date getFinanceEndDate() {
		return get("finance_end_date");
	}

	public M setPayDate(java.lang.String payDate) {
		set("pay_date", payDate);
		return (M)this;
	}

	public java.lang.String getPayDate() {
		return get("pay_date");
	}

	public M setOrderCompleteDate(java.lang.String orderCompleteDate) {
		set("order_complete_date", orderCompleteDate);
		return (M)this;
	}

	public java.lang.String getOrderCompleteDate() {
		return get("order_complete_date");
	}

	public M setPayType(java.lang.String payType) {
		set("pay_type", payType);
		return (M)this;
	}

	public java.lang.String getPayType() {
		return get("pay_type");
	}

	public M setRepayDate(java.util.Date repayDate) {
		set("repay_date", repayDate);
		return (M)this;
	}

	public java.util.Date getRepayDate() {
		return get("repay_date");
	}

	public M setItemPrefix(java.lang.String itemPrefix) {
		set("item_prefix", itemPrefix);
		return (M)this;
	}

	public java.lang.String getItemPrefix() {
		return get("item_prefix");
	}

}
