package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePaymentPort<M extends BasePaymentPort<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setTxCode(java.lang.String txCode) {
		set("tx_code", txCode);
		return (M)this;
	}

	public java.lang.String getTxCode() {
		return get("tx_code");
	}

	public M setInstitutionId(java.lang.String institutionId) {
		set("institution_id", institutionId);
		return (M)this;
	}

	public java.lang.String getInstitutionId() {
		return get("institution_id");
	}

	public M setFkOrderId(java.lang.String fkOrderId) {
		set("fk_order_id", fkOrderId);
		return (M)this;
	}

	public java.lang.String getFkOrderId() {
		return get("fk_order_id");
	}

	public M setSerialNumber(java.lang.String serialNumber) {
		set("serial_number", serialNumber);
		return (M)this;
	}

	public java.lang.String getSerialNumber() {
		return get("serial_number");
	}

	public M setOrderNumber(java.lang.String orderNumber) {
		set("order_number", orderNumber);
		return (M)this;
	}

	public java.lang.String getOrderNumber() {
		return get("order_number");
	}

	public M setPayMentNumber(java.lang.String payMentNumber) {
		set("pay_ment_number", payMentNumber);
		return (M)this;
	}

	public java.lang.String getPayMentNumber() {
		return get("pay_ment_number");
	}

	public M setQuickPaymentNumber(java.lang.String quickPaymentNumber) {
		set("quick_payment_number", quickPaymentNumber);
		return (M)this;
	}

	public java.lang.String getQuickPaymentNumber() {
		return get("quick_payment_number");
	}

	public M setAmount(java.lang.String amount) {
		set("amount", amount);
		return (M)this;
	}

	public java.lang.String getAmount() {
		return get("amount");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setAccountCode(java.lang.String accountCode) {
		set("account_code", accountCode);
		return (M)this;
	}

	public java.lang.String getAccountCode() {
		return get("account_code");
	}

	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}

	public java.lang.String getAccountName() {
		return get("account_name");
	}

	public M setAccSeq(java.lang.String accSeq) {
		set("acc_seq", accSeq);
		return (M)this;
	}

	public java.lang.String getAccSeq() {
		return get("acc_seq");
	}

	public M setEacName(java.lang.String eacName) {
		set("eac_name", eacName);
		return (M)this;
	}

	public java.lang.String getEacName() {
		return get("eac_name");
	}

	public M setEacNumber(java.lang.String eacNumber) {
		set("eac_number", eacNumber);
		return (M)this;
	}

	public java.lang.String getEacNumber() {
		return get("eac_number");
	}

	public M setAccountBank(java.lang.String accountBank) {
		set("account_bank", accountBank);
		return (M)this;
	}

	public java.lang.String getAccountBank() {
		return get("account_bank");
	}

	public M setAccountBankId(java.lang.String accountBankId) {
		set("account_bank_id", accountBankId);
		return (M)this;
	}

	public java.lang.String getAccountBankId() {
		return get("account_bank_id");
	}

	public M setProvinceCode(java.lang.String provinceCode) {
		set("province_code", provinceCode);
		return (M)this;
	}

	public java.lang.String getProvinceCode() {
		return get("province_code");
	}

	public M setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
		return (M)this;
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public M setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
		return (M)this;
	}

	public java.lang.String getCityCode() {
		return get("city_code");
	}

	public M setCityName(java.lang.String cityName) {
		set("city_name", cityName);
		return (M)this;
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public M setSubBankId(java.lang.String subBankId) {
		set("sub_bank_id", subBankId);
		return (M)this;
	}

	public java.lang.String getSubBankId() {
		return get("sub_bank_id");
	}

	public M setBrdnbr(java.lang.String brdnbr) {
		set("brdnbr", brdnbr);
		return (M)this;
	}

	public java.lang.String getBrdnbr() {
		return get("brdnbr");
	}

	public M setCertificateType(java.lang.String certificateType) {
		set("certificate_type", certificateType);
		return (M)this;
	}

	public java.lang.String getCertificateType() {
		return get("certificate_type");
	}

	public M setCertificateNumber(java.lang.String certificateNumber) {
		set("certificate_number", certificateNumber);
		return (M)this;
	}

	public java.lang.String getCertificateNumber() {
		return get("certificate_number");
	}

	public M setPersonType(java.lang.String personType) {
		set("person_type", personType);
		return (M)this;
	}

	public java.lang.String getPersonType() {
		return get("person_type");
	}

	public M setSigTime(java.util.Date sigTime) {
		set("sig_time", sigTime);
		return (M)this;
	}

	public java.util.Date getSigTime() {
		return get("sig_time");
	}

	public M setCheckType(java.lang.String checkType) {
		set("check_type", checkType);
		return (M)this;
	}

	public java.lang.String getCheckType() {
		return get("check_type");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setRecontent(java.lang.String recontent) {
		set("recontent", recontent);
		return (M)this;
	}

	public java.lang.String getRecontent() {
		return get("recontent");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setExchangeStatus(java.lang.String exchangeStatus) {
		set("exchange_status", exchangeStatus);
		return (M)this;
	}

	public java.lang.String getExchangeStatus() {
		return get("exchange_status");
	}

	public M setExchangeMessage(java.lang.String exchangeMessage) {
		set("exchange_message", exchangeMessage);
		return (M)this;
	}

	public java.lang.String getExchangeMessage() {
		return get("exchange_message");
	}

}
