package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAwardChanceInfo<M extends BaseAwardChanceInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setFkBaseInfoId(java.lang.String fkBaseInfoId) {
		set("fk_base_info_id", fkBaseInfoId);
		return (M)this;
	}

	public java.lang.String getFkBaseInfoId() {
		return get("fk_base_info_id");
	}

	public M setFkItemId(java.lang.String fkItemId) {
		set("fk_item_id", fkItemId);
		return (M)this;
	}

	public java.lang.String getFkItemId() {
		return get("fk_item_id");
	}

	public M setCoinType(java.lang.String coinType) {
		set("coin_type", coinType);
		return (M)this;
	}

	public java.lang.String getCoinType() {
		return get("coin_type");
	}

	public M setClientType(java.lang.String clientType) {
		set("client_type", clientType);
		return (M)this;
	}

	public java.lang.String getClientType() {
		return get("client_type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setIsUsed(java.lang.String isUsed) {
		set("is_used", isUsed);
		return (M)this;
	}

	public java.lang.String getIsUsed() {
		return get("is_used");
	}

}
