package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUsedAwardInfo<M extends BaseUsedAwardInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setFkBaseInfoId(java.lang.String fkBaseInfoId) {
		set("fk_base_info_id", fkBaseInfoId);
		return (M)this;
	}

	public java.lang.String getFkBaseInfoId() {
		return get("fk_base_info_id");
	}

	public M setFkOrderId(java.lang.String fkOrderId) {
		set("fk_order_id", fkOrderId);
		return (M)this;
	}

	public java.lang.String getFkOrderId() {
		return get("fk_order_id");
	}

	public M setFkAwardId(java.lang.String fkAwardId) {
		set("fk_award_id", fkAwardId);
		return (M)this;
	}

	public java.lang.String getFkAwardId() {
		return get("fk_award_id");
	}

	public M setUsedCoinNum(java.lang.String usedCoinNum) {
		set("used_coin_num", usedCoinNum);
		return (M)this;
	}

	public java.lang.String getUsedCoinNum() {
		return get("used_coin_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setInvalidTime(java.util.Date invalidTime) {
		set("invalid_time", invalidTime);
		return (M)this;
	}

	public java.util.Date getInvalidTime() {
		return get("invalid_time");
	}

	public M setIsValid(java.lang.String isValid) {
		set("is_valid", isValid);
		return (M)this;
	}

	public java.lang.String getIsValid() {
		return get("is_valid");
	}

	public M setClientType(java.lang.String clientType) {
		set("client_type", clientType);
		return (M)this;
	}

	public java.lang.String getClientType() {
		return get("client_type");
	}

}
