package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMessageContent<M extends BaseMessageContent<M>> extends Model<M> implements IBean {

	public M setId(java.lang.String id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.String getId() {
		return get("id");
	}

	public M setBaseinfoId(java.lang.String baseinfoId) {
		set("baseinfo_id", baseinfoId);
		return (M)this;
	}

	public java.lang.String getBaseinfoId() {
		return get("baseinfo_id");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public M setCreatDate(java.lang.String creatDate) {
		set("creat_date", creatDate);
		return (M)this;
	}

	public java.lang.String getCreatDate() {
		return get("creat_date");
	}

	public M setOredrId(java.lang.String oredrId) {
		set("oredr_id", oredrId);
		return (M)this;
	}

	public java.lang.String getOredrId() {
		return get("oredr_id");
	}

	public M setPram1(java.lang.String pram1) {
		set("pram1", pram1);
		return (M)this;
	}

	public java.lang.String getPram1() {
		return get("pram1");
	}

	public M setPram2(java.lang.String pram2) {
		set("pram2", pram2);
		return (M)this;
	}

	public java.lang.String getPram2() {
		return get("pram2");
	}

	public M setPram3(java.lang.String pram3) {
		set("pram3", pram3);
		return (M)this;
	}

	public java.lang.String getPram3() {
		return get("pram3");
	}

	public M setState(java.lang.String state) {
		set("state", state);
		return (M)this;
	}

	public java.lang.String getState() {
		return get("state");
	}

}
