package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePersonAccountInfo<M extends BasePersonAccountInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setAccountName(java.lang.String accountName) {
		set("account_name", accountName);
		return (M)this;
	}

	public java.lang.String getAccountName() {
		return get("account_name");
	}

	public M setAccountCode(java.lang.String accountCode) {
		set("account_code", accountCode);
		return (M)this;
	}

	public java.lang.String getAccountCode() {
		return get("account_code");
	}

	public M setCardNumber(java.lang.String cardNumber) {
		set("card_number", cardNumber);
		return (M)this;
	}

	public java.lang.String getCardNumber() {
		return get("card_number");
	}

	public M setCardBank(java.lang.String cardBank) {
		set("card_bank", cardBank);
		return (M)this;
	}

	public java.lang.String getCardBank() {
		return get("card_bank");
	}

	public M setCardSubBank(java.lang.String cardSubBank) {
		set("card_sub_bank", cardSubBank);
		return (M)this;
	}

	public java.lang.String getCardSubBank() {
		return get("card_sub_bank");
	}

	public M setCardProvince(java.lang.String cardProvince) {
		set("card_province", cardProvince);
		return (M)this;
	}

	public java.lang.String getCardProvince() {
		return get("card_province");
	}

	public M setCardCity(java.lang.String cardCity) {
		set("card_city", cardCity);
		return (M)this;
	}

	public java.lang.String getCardCity() {
		return get("card_city");
	}

	public M setFkBaseInfoId(java.lang.String fkBaseInfoId) {
		set("fk_base_info_id", fkBaseInfoId);
		return (M)this;
	}

	public java.lang.String getFkBaseInfoId() {
		return get("fk_base_info_id");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}

	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public M setProvinceName(java.lang.String provinceName) {
		set("province_name", provinceName);
		return (M)this;
	}

	public java.lang.String getProvinceName() {
		return get("province_name");
	}

	public M setCityName(java.lang.String cityName) {
		set("city_name", cityName);
		return (M)this;
	}

	public java.lang.String getCityName() {
		return get("city_name");
	}

	public M setBindingState(java.lang.String bindingState) {
		set("binding_state", bindingState);
		return (M)this;
	}

	public java.lang.String getBindingState() {
		return get("binding_state");
	}

	public M setBindingMobiePhone(java.lang.String bindingMobiePhone) {
		set("binding_mobie_phone", bindingMobiePhone);
		return (M)this;
	}

	public java.lang.String getBindingMobiePhone() {
		return get("binding_mobie_phone");
	}

	public M setBindingNumber(java.lang.String bindingNumber) {
		set("binding_number", bindingNumber);
		return (M)this;
	}

	public java.lang.String getBindingNumber() {
		return get("binding_number");
	}

	public M setBindingTime(java.lang.String bindingTime) {
		set("binding_time", bindingTime);
		return (M)this;
	}

	public java.lang.String getBindingTime() {
		return get("binding_time");
	}

	public M setBingdingClientType(java.lang.String bingdingClientType) {
		set("bingding_client_type", bingdingClientType);
		return (M)this;
	}

	public java.lang.String getBingdingClientType() {
		return get("bingding_client_type");
	}

	public M setFailReason(java.lang.String failReason) {
		set("fail_reason", failReason);
		return (M)this;
	}

	public java.lang.String getFailReason() {
		return get("fail_reason");
	}

	public M setUnbundlingClientType(java.lang.String unbundlingClientType) {
		set("unbundling_client_type", unbundlingClientType);
		return (M)this;
	}

	public java.lang.String getUnbundlingClientType() {
		return get("unbundling_client_type");
	}

	public M setUnbundlingTime(java.lang.String unbundlingTime) {
		set("unbundling_time", unbundlingTime);
		return (M)this;
	}

	public java.lang.String getUnbundlingTime() {
		return get("unbundling_time");
	}

}
