package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysMenu<M extends BaseSysMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return get("name");
	}

	public M setLeaf(java.lang.String leaf) {
		set("leaf", leaf);
		return (M)this;
	}

	public java.lang.String getLeaf() {
		return get("leaf");
	}

	public M setPid(java.lang.String pid) {
		set("pid", pid);
		return (M)this;
	}

	public java.lang.String getPid() {
		return get("pid");
	}

}
