package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseFinanceClearList<M extends BaseFinanceClearList<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setLoanType(java.lang.String loanType) {
		set("loan_type", loanType);
		return (M)this;
	}

	public java.lang.String getLoanType() {
		return get("loan_type");
	}

	public M setLoanCode(java.lang.String loanCode) {
		set("loan_code", loanCode);
		return (M)this;
	}

	public java.lang.String getLoanCode() {
		return get("loan_code");
	}

	public M setLoanMount(java.math.BigDecimal loanMount) {
		set("loan_mount", loanMount);
		return (M)this;
	}

	public java.math.BigDecimal getLoanMount() {
		return get("loan_mount");
	}

	public M setBankType(java.lang.String bankType) {
		set("bank_type", bankType);
		return (M)this;
	}

	public java.lang.String getBankType() {
		return get("bank_type");
	}

	public M setBankCardNo(java.lang.String bankCardNo) {
		set("bank_card_no", bankCardNo);
		return (M)this;
	}

	public java.lang.String getBankCardNo() {
		return get("bank_card_no");
	}

	public M setBankAccount(java.lang.String bankAccount) {
		set("bank_account", bankAccount);
		return (M)this;
	}

	public java.lang.String getBankAccount() {
		return get("bank_account");
	}

	public M setBankId(java.lang.String bankId) {
		set("bank_id", bankId);
		return (M)this;
	}

	public java.lang.String getBankId() {
		return get("bank_id");
	}

	public M setBankName(java.lang.String bankName) {
		set("bank_name", bankName);
		return (M)this;
	}

	public java.lang.String getBankName() {
		return get("bank_name");
	}

	public M setProvincCode(java.lang.String provincCode) {
		set("provinc_code", provincCode);
		return (M)this;
	}

	public java.lang.String getProvincCode() {
		return get("provinc_code");
	}

	public M setProvince(java.lang.String province) {
		set("province", province);
		return (M)this;
	}

	public java.lang.String getProvince() {
		return get("province");
	}

	public M setCityCode(java.lang.String cityCode) {
		set("city_code", cityCode);
		return (M)this;
	}

	public java.lang.String getCityCode() {
		return get("city_code");
	}

	public M setCity(java.lang.String city) {
		set("city", city);
		return (M)this;
	}

	public java.lang.String getCity() {
		return get("city");
	}

	public M setBranchBank(java.lang.String branchBank) {
		set("branch_bank", branchBank);
		return (M)this;
	}

	public java.lang.String getBranchBank() {
		return get("branch_bank");
	}

	public M setDesrc(java.lang.String desrc) {
		set("desrc", desrc);
		return (M)this;
	}

	public java.lang.String getDesrc() {
		return get("desrc");
	}

	public M setStatus(java.lang.String status) {
		set("status", status);
		return (M)this;
	}

	public java.lang.String getStatus() {
		return get("status");
	}

	public M setItemId(java.lang.String itemId) {
		set("item_id", itemId);
		return (M)this;
	}

	public java.lang.String getItemId() {
		return get("item_id");
	}

	public M setItemName(java.lang.String itemName) {
		set("item_name", itemName);
		return (M)this;
	}

	public java.lang.String getItemName() {
		return get("item_name");
	}

	public M setDeductionFee(java.lang.String deductionFee) {
		set("deduction_fee", deductionFee);
		return (M)this;
	}

	public java.lang.String getDeductionFee() {
		return get("deduction_fee");
	}

}
