package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseItemInfo<M extends BaseItemInfo<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setItemName(java.lang.String itemName) {
		set("item_name", itemName);
		return (M)this;
	}

	public java.lang.String getItemName() {
		return get("item_name");
	}

	public M setItemNo(java.lang.String itemNo) {
		set("item_no", itemNo);
		return (M)this;
	}

	public java.lang.String getItemNo() {
		return get("item_no");
	}

	public M setSpecialFlag(java.lang.String specialFlag) {
		set("special_flag", specialFlag);
		return (M)this;
	}

	public java.lang.String getSpecialFlag() {
		return get("special_flag");
	}

	public M setOpenFlag(java.lang.String openFlag) {
		set("open_flag", openFlag);
		return (M)this;
	}

	public java.lang.String getOpenFlag() {
		return get("open_flag");
	}

	public M setWhiteFlag(java.lang.String whiteFlag) {
		set("white_flag", whiteFlag);
		return (M)this;
	}

	public java.lang.String getWhiteFlag() {
		return get("white_flag");
	}

	public M setInvestorCode(java.lang.String investorCode) {
		set("investor_code", investorCode);
		return (M)this;
	}

	public java.lang.String getInvestorCode() {
		return get("investor_code");
	}

	public M setRepayType(java.lang.String repayType) {
		set("repay_type", repayType);
		return (M)this;
	}

	public java.lang.String getRepayType() {
		return get("repay_type");
	}

	public M setRepaySource(java.lang.String repaySource) {
		set("repay_source", repaySource);
		return (M)this;
	}

	public java.lang.String getRepaySource() {
		return get("repay_source");
	}

	public M setRepaySourceType(java.lang.String repaySourceType) {
		set("repay_source_type", repaySourceType);
		return (M)this;
	}

	public java.lang.String getRepaySourceType() {
		return get("repay_source_type");
	}

	public M setRepaySourceContent(java.lang.String repaySourceContent) {
		set("repay_source_content", repaySourceContent);
		return (M)this;
	}

	public java.lang.String getRepaySourceContent() {
		return get("repay_source_content");
	}

	public M setPreheatingStartDate(java.util.Date preheatingStartDate) {
		set("preheating_start_date", preheatingStartDate);
		return (M)this;
	}

	public java.util.Date getPreheatingStartDate() {
		return get("preheating_start_date");
	}

	public M setInvestStartDate(java.util.Date investStartDate) {
		set("invest_start_date", investStartDate);
		return (M)this;
	}

	public java.util.Date getInvestStartDate() {
		return get("invest_start_date");
	}

	public M setInvestEndDate(java.util.Date investEndDate) {
		set("invest_end_date", investEndDate);
		return (M)this;
	}

	public java.util.Date getInvestEndDate() {
		return get("invest_end_date");
	}

	public M setFinanceClearDate(java.util.Date financeClearDate) {
		set("finance_clear_date", financeClearDate);
		return (M)this;
	}

	public java.util.Date getFinanceClearDate() {
		return get("finance_clear_date");
	}

	public M setRealFinanceClearDate(java.util.Date realFinanceClearDate) {
		set("real_finance_clear_date", realFinanceClearDate);
		return (M)this;
	}

	public java.util.Date getRealFinanceClearDate() {
		return get("real_finance_clear_date");
	}

	public M setInterestStartDate(java.util.Date interestStartDate) {
		set("interest_start_date", interestStartDate);
		return (M)this;
	}

	public java.util.Date getInterestStartDate() {
		return get("interest_start_date");
	}

	public M setCreditCardEndDate(java.util.Date creditCardEndDate) {
		set("credit_card_end_date", creditCardEndDate);
		return (M)this;
	}

	public java.util.Date getCreditCardEndDate() {
		return get("credit_card_end_date");
	}

	public M setFinanceEndDate(java.util.Date financeEndDate) {
		set("finance_end_date", financeEndDate);
		return (M)this;
	}

	public java.util.Date getFinanceEndDate() {
		return get("finance_end_date");
	}

	public M setRepayClearDate(java.util.Date repayClearDate) {
		set("repay_clear_date", repayClearDate);
		return (M)this;
	}

	public java.util.Date getRepayClearDate() {
		return get("repay_clear_date");
	}

	public M setRealRepayClearDate(java.util.Date realRepayClearDate) {
		set("real_repay_clear_date", realRepayClearDate);
		return (M)this;
	}

	public java.util.Date getRealRepayClearDate() {
		return get("real_repay_clear_date");
	}

	public M setHeadBankPassDate(java.util.Date headBankPassDate) {
		set("head_bank_pass_date", headBankPassDate);
		return (M)this;
	}

	public java.util.Date getHeadBankPassDate() {
		return get("head_bank_pass_date");
	}

	public M setCreatePrjDate(java.util.Date createPrjDate) {
		set("create_prj_date", createPrjDate);
		return (M)this;
	}

	public java.util.Date getCreatePrjDate() {
		return get("create_prj_date");
	}

	public M setFinancePeriod(java.math.BigDecimal financePeriod) {
		set("finance_period", financePeriod);
		return (M)this;
	}

	public java.math.BigDecimal getFinancePeriod() {
		return get("finance_period");
	}

	public M setInvesterYearRate(java.math.BigDecimal investerYearRate) {
		set("invester_year_rate", investerYearRate);
		return (M)this;
	}

	public java.math.BigDecimal getInvesterYearRate() {
		return get("invester_year_rate");
	}

	public M setPlatformServiceRateYear(java.math.BigDecimal platformServiceRateYear) {
		set("platform_service_rate_year", platformServiceRateYear);
		return (M)this;
	}

	public java.math.BigDecimal getPlatformServiceRateYear() {
		return get("platform_service_rate_year");
	}

	public M setFinanciersRates(java.math.BigDecimal financiersRates) {
		set("financiers_rates", financiersRates);
		return (M)this;
	}

	public java.math.BigDecimal getFinanciersRates() {
		return get("financiers_rates");
	}

	public M setMinInvestAmount(java.lang.Integer minInvestAmount) {
		set("min_invest_amount", minInvestAmount);
		return (M)this;
	}

	public java.lang.Integer getMinInvestAmount() {
		return get("min_invest_amount");
	}

	public M setInvestUnitFee(java.math.BigDecimal investUnitFee) {
		set("invest_unit_fee", investUnitFee);
		return (M)this;
	}

	public java.math.BigDecimal getInvestUnitFee() {
		return get("invest_unit_fee");
	}

	public M setTotalFinanceMoney(java.math.BigDecimal totalFinanceMoney) {
		set("total_finance_money", totalFinanceMoney);
		return (M)this;
	}

	public java.math.BigDecimal getTotalFinanceMoney() {
		return get("total_finance_money");
	}

	public M setMaxFinanceMoney(java.math.BigDecimal maxFinanceMoney) {
		set("max_finance_money", maxFinanceMoney);
		return (M)this;
	}

	public java.math.BigDecimal getMaxFinanceMoney() {
		return get("max_finance_money");
	}

	public M setSettlementType(java.lang.String settlementType) {
		set("settlement_type", settlementType);
		return (M)this;
	}

	public java.lang.String getSettlementType() {
		return get("settlement_type");
	}

	public M setTotalHandMoney(java.math.BigDecimal totalHandMoney) {
		set("total_hand_money", totalHandMoney);
		return (M)this;
	}

	public java.math.BigDecimal getTotalHandMoney() {
		return get("total_hand_money");
	}

	public M setFinanceFullInterest(java.math.BigDecimal financeFullInterest) {
		set("finance_full_interest", financeFullInterest);
		return (M)this;
	}

	public java.math.BigDecimal getFinanceFullInterest() {
		return get("finance_full_interest");
	}

	public M setFinancePlatformFee(java.math.BigDecimal financePlatformFee) {
		set("finance_platform_fee", financePlatformFee);
		return (M)this;
	}

	public java.math.BigDecimal getFinancePlatformFee() {
		return get("finance_platform_fee");
	}

	public M setFinanceFullPromiseFee(java.math.BigDecimal financeFullPromiseFee) {
		set("finance_full_promise_fee", financeFullPromiseFee);
		return (M)this;
	}

	public java.math.BigDecimal getFinanceFullPromiseFee() {
		return get("finance_full_promise_fee");
	}

	public M setSubBankYearRate(java.math.BigDecimal subBankYearRate) {
		set("sub_bank_year_rate", subBankYearRate);
		return (M)this;
	}

	public java.math.BigDecimal getSubBankYearRate() {
		return get("sub_bank_year_rate");
	}

	public M setSubBankServiceFee(java.math.BigDecimal subBankServiceFee) {
		set("sub_bank_service_fee", subBankServiceFee);
		return (M)this;
	}

	public java.math.BigDecimal getSubBankServiceFee() {
		return get("sub_bank_service_fee");
	}

	public M setFinanceUsername(java.lang.String financeUsername) {
		set("finance_username", financeUsername);
		return (M)this;
	}

	public java.lang.String getFinanceUsername() {
		return get("finance_username");
	}

	public M setCompanyName(java.lang.String companyName) {
		set("company_name", companyName);
		return (M)this;
	}

	public java.lang.String getCompanyName() {
		return get("company_name");
	}

	public M setFinanceMobilePhone(java.lang.String financeMobilePhone) {
		set("finance_mobile_phone", financeMobilePhone);
		return (M)this;
	}

	public java.lang.String getFinanceMobilePhone() {
		return get("finance_mobile_phone");
	}

	public M setFinanceAccountName(java.lang.String financeAccountName) {
		set("finance_account_name", financeAccountName);
		return (M)this;
	}

	public java.lang.String getFinanceAccountName() {
		return get("finance_account_name");
	}

	public M setFinanceAccountBank(java.lang.String financeAccountBank) {
		set("finance_account_bank", financeAccountBank);
		return (M)this;
	}

	public java.lang.String getFinanceAccountBank() {
		return get("finance_account_bank");
	}

	public M setFinanceAccountNo(java.lang.String financeAccountNo) {
		set("finance_account_no", financeAccountNo);
		return (M)this;
	}

	public java.lang.String getFinanceAccountNo() {
		return get("finance_account_no");
	}

	public M setFinanceAccountProvince(java.lang.String financeAccountProvince) {
		set("finance_account_province", financeAccountProvince);
		return (M)this;
	}

	public java.lang.String getFinanceAccountProvince() {
		return get("finance_account_province");
	}

	public M setFinanceAccountCity(java.lang.String financeAccountCity) {
		set("finance_account_city", financeAccountCity);
		return (M)this;
	}

	public java.lang.String getFinanceAccountCity() {
		return get("finance_account_city");
	}

	public M setFinanceAccountSubBankName(java.lang.String financeAccountSubBankName) {
		set("finance_account_sub_bank_name", financeAccountSubBankName);
		return (M)this;
	}

	public java.lang.String getFinanceAccountSubBankName() {
		return get("finance_account_sub_bank_name");
	}

	public M setFinanceAccountSubBankCode(java.lang.String financeAccountSubBankCode) {
		set("finance_account_sub_bank_code", financeAccountSubBankCode);
		return (M)this;
	}

	public java.lang.String getFinanceAccountSubBankCode() {
		return get("finance_account_sub_bank_code");
	}

	public M setFinanceAccountSubBankNameTemp(java.lang.String financeAccountSubBankNameTemp) {
		set("finance_account_sub_bank_name_temp", financeAccountSubBankNameTemp);
		return (M)this;
	}

	public java.lang.String getFinanceAccountSubBankNameTemp() {
		return get("finance_account_sub_bank_name_temp");
	}

	public M setFinanceCreditCheck(java.lang.String financeCreditCheck) {
		set("finance_credit_check", financeCreditCheck);
		return (M)this;
	}

	public java.lang.String getFinanceCreditCheck() {
		return get("finance_credit_check");
	}

	public M setFinanceFinishOtherCheck(java.lang.String financeFinishOtherCheck) {
		set("finance_finish_other_check", financeFinishOtherCheck);
		return (M)this;
	}

	public java.lang.String getFinanceFinishOtherCheck() {
		return get("finance_finish_other_check");
	}

	public M setItemDtlInfoStr(java.lang.String itemDtlInfoStr) {
		set("item_dtl_info_str", itemDtlInfoStr);
		return (M)this;
	}

	public java.lang.String getItemDtlInfoStr() {
		return get("item_dtl_info_str");
	}

	public M setItemDtlInfo(java.lang.String itemDtlInfo) {
		set("item_dtl_info", itemDtlInfo);
		return (M)this;
	}

	public java.lang.String getItemDtlInfo() {
		return get("item_dtl_info");
	}

	public M setItemNoteInfo(java.lang.String itemNoteInfo) {
		set("item_note_info", itemNoteInfo);
		return (M)this;
	}

	public java.lang.String getItemNoteInfo() {
		return get("item_note_info");
	}

	public M setItemAllStatus(java.lang.String itemAllStatus) {
		set("item_all_status", itemAllStatus);
		return (M)this;
	}

	public java.lang.String getItemAllStatus() {
		return get("item_all_status");
	}

	public M setItemListFlag(java.lang.String itemListFlag) {
		set("item_list_flag", itemListFlag);
		return (M)this;
	}

	public java.lang.String getItemListFlag() {
		return get("item_list_flag");
	}

	public M setItemApproveStatus(java.lang.String itemApproveStatus) {
		set("item_approve_status", itemApproveStatus);
		return (M)this;
	}

	public java.lang.String getItemApproveStatus() {
		return get("item_approve_status");
	}

	public M setProgressFront(java.lang.String progressFront) {
		set("progress_front", progressFront);
		return (M)this;
	}

	public java.lang.String getProgressFront() {
		return get("progress_front");
	}

	public M setProgressBack(java.lang.String progressBack) {
		set("progress_back", progressBack);
		return (M)this;
	}

	public java.lang.String getProgressBack() {
		return get("progress_back");
	}

	public M setSubRefuseStr(java.lang.String subRefuseStr) {
		set("sub_refuse_str", subRefuseStr);
		return (M)this;
	}

	public java.lang.String getSubRefuseStr() {
		return get("sub_refuse_str");
	}

	public M setHeadRefuseStr(java.lang.String headRefuseStr) {
		set("head_refuse_str", headRefuseStr);
		return (M)this;
	}

	public java.lang.String getHeadRefuseStr() {
		return get("head_refuse_str");
	}

	public M setLastRefuseStr(java.lang.String lastRefuseStr) {
		set("last_refuse_str", lastRefuseStr);
		return (M)this;
	}

	public java.lang.String getLastRefuseStr() {
		return get("last_refuse_str");
	}

	public M setItemPayStatus(java.lang.String itemPayStatus) {
		set("item_pay_status", itemPayStatus);
		return (M)this;
	}

	public java.lang.String getItemPayStatus() {
		return get("item_pay_status");
	}

	public M setItemRepayStatus(java.lang.String itemRepayStatus) {
		set("item_repay_status", itemRepayStatus);
		return (M)this;
	}

	public java.lang.String getItemRepayStatus() {
		return get("item_repay_status");
	}

	public M setItemPrefix(java.lang.String itemPrefix) {
		set("item_prefix", itemPrefix);
		return (M)this;
	}

	public java.lang.String getItemPrefix() {
		return get("item_prefix");
	}

	public M setSubBankCode(java.lang.String subBankCode) {
		set("sub_bank_code", subBankCode);
		return (M)this;
	}

	public java.lang.String getSubBankCode() {
		return get("sub_bank_code");
	}

	public M setFullFlag(java.lang.String fullFlag) {
		set("full_flag", fullFlag);
		return (M)this;
	}

	public java.lang.String getFullFlag() {
		return get("full_flag");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public M setItemRepayFlag(java.lang.String itemRepayFlag) {
		set("item_repay_flag", itemRepayFlag);
		return (M)this;
	}

	public java.lang.String getItemRepayFlag() {
		return get("item_repay_flag");
	}

	public M setContractNumber(java.lang.String contractNumber) {
		set("contract_number", contractNumber);
		return (M)this;
	}

	public java.lang.String getContractNumber() {
		return get("contract_number");
	}

	public M setLoanApplyNumber(java.lang.String loanApplyNumber) {
		set("loan_apply_number", loanApplyNumber);
		return (M)this;
	}

	public java.lang.String getLoanApplyNumber() {
		return get("loan_apply_number");
	}

	public M setOrganizationNumber(java.lang.String organizationNumber) {
		set("organization_number", organizationNumber);
		return (M)this;
	}

	public java.lang.String getOrganizationNumber() {
		return get("organization_number");
	}

	public M setLoanDate(java.util.Date loanDate) {
		set("loan_date", loanDate);
		return (M)this;
	}

	public java.util.Date getLoanDate() {
		return get("loan_date");
	}

	public M setItemType(java.lang.String itemType) {
		set("item_type", itemType);
		return (M)this;
	}

	public java.lang.String getItemType() {
		return get("item_type");
	}

	public M setOldInvestEndDate(java.util.Date oldInvestEndDate) {
		set("old_invest_end_date", oldInvestEndDate);
		return (M)this;
	}

	public java.util.Date getOldInvestEndDate() {
		return get("old_invest_end_date");
	}

	public M setIsChange(java.lang.String isChange) {
		set("is_change", isChange);
		return (M)this;
	}

	public java.lang.String getIsChange() {
		return get("is_change");
	}

	public M setNewUserQuota(java.lang.String newUserQuota) {
		set("new_user_quota", newUserQuota);
		return (M)this;
	}

	public java.lang.String getNewUserQuota() {
		return get("new_user_quota");
	}

	public M setIsNewExclusive(java.lang.String isNewExclusive) {
		set("is_new_exclusive", isNewExclusive);
		return (M)this;
	}

	public java.lang.String getIsNewExclusive() {
		return get("is_new_exclusive");
	}

	public M setTicketRatio(java.lang.String ticketRatio) {
		set("ticket_ratio", ticketRatio);
		return (M)this;
	}

	public java.lang.String getTicketRatio() {
		return get("ticket_ratio");
	}

	public M setPrintReceiptNum(java.lang.String printReceiptNum) {
		set("print_receipt_num", printReceiptNum);
		return (M)this;
	}

	public java.lang.String getPrintReceiptNum() {
		return get("print_receipt_num");
	}

	public M setItemStatusTemp(java.lang.String itemStatusTemp) {
		set("item_status_temp", itemStatusTemp);
		return (M)this;
	}

	public java.lang.String getItemStatusTemp() {
		return get("item_status_temp");
	}

}
