package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRoleMenu<M extends BaseRoleMenu<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setSysRoleId(java.lang.String sysRoleId) {
		set("sys_role_id", sysRoleId);
		return (M)this;
	}

	public java.lang.String getSysRoleId() {
		return get("sys_role_id");
	}

	public M setSysMenuId(java.lang.String sysMenuId) {
		set("sys_menu_id", sysMenuId);
		return (M)this;
	}

	public java.lang.String getSysMenuId() {
		return get("sys_menu_id");
	}

}
