package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDicSystem<M extends BaseDicSystem<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setText(java.lang.String text) {
		set("text", text);
		return (M)this;
	}

	public java.lang.String getText() {
		return get("text");
	}

	public M setCode(java.lang.String code) {
		set("code", code);
		return (M)this;
	}

	public java.lang.String getCode() {
		return get("code");
	}

	public M setEncoding(java.lang.String encoding) {
		set("encoding", encoding);
		return (M)this;
	}

	public java.lang.String getEncoding() {
		return get("encoding");
	}

	public M setScn(java.lang.String scn) {
		set("scn", scn);
		return (M)this;
	}

	public java.lang.String getScn() {
		return get("scn");
	}

	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}

	public java.lang.String getType() {
		return get("type");
	}

	public M setBigType(java.lang.String bigType) {
		set("big_type", bigType);
		return (M)this;
	}

	public java.lang.String getBigType() {
		return get("big_type");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public M setStatue(java.lang.Integer statue) {
		set("statue", statue);
		return (M)this;
	}

	public java.lang.Integer getStatue() {
		return get("statue");
	}

	public M setMaxLimit(java.lang.String maxLimit) {
		set("max_limit", maxLimit);
		return (M)this;
	}

	public java.lang.String getMaxLimit() {
		return get("max_limit");
	}

}
