package com.maiseries.core.bank.web.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSysUser<M extends BaseSysUser<M>> extends Model<M> implements IBean {

	public M setID(java.lang.String ID) {
		set("ID", ID);
		return (M)this;
	}

	public java.lang.String getID() {
		return get("ID");
	}

	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}

	public java.lang.String getUserName() {
		return get("user_name");
	}

	public M setMobilePhone(java.lang.String mobilePhone) {
		set("mobile_phone", mobilePhone);
		return (M)this;
	}

	public java.lang.String getMobilePhone() {
		return get("mobile_phone");
	}

	public M setSubBankCode(java.lang.String subBankCode) {
		set("sub_bank_code", subBankCode);
		return (M)this;
	}

	public java.lang.String getSubBankCode() {
		return get("sub_bank_code");
	}

	public M setSubBankName(java.lang.String subBankName) {
		set("sub_bank_name", subBankName);
		return (M)this;
	}

	public java.lang.String getSubBankName() {
		return get("sub_bank_name");
	}

	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setSysRoleId(java.lang.String sysRoleId) {
		set("sys_role_id", sysRoleId);
		return (M)this;
	}

	public java.lang.String getSysRoleId() {
		return get("sys_role_id");
	}

}
